<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;

function w_select_with_image_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {
  //dpm($form_id);
  if ($form_id == 'node_order_form') {
    w_select_with_image_form_node_order_form_alter($form, $form_state);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Example: article node form + field_colors taxonomy term reference.
 */
function w_select_with_image_form_node_order_form_alter(array &$form, FormStateInterface $form_state) {

  // Get available colors by master code.
  $route_match = \Drupal::routeMatch();
  $nid = $route_match->getParameter('node');
  if ($nid instanceof NodeInterface) {
    $nid = $nid->id();
  }

  $nid = is_numeric($nid) ? (int) $nid : null;
  $product = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
  $masterCode = $product->get('field_master_code')->getValue()[0]['value'];

  $colors = \Drupal::service('w_solo_api.get_colors')->getColors($masterCode);

  $form['field_product']['#default_value'] = $product->id();

  $el =& $form['field_order_options']['widget'][0]['subform']['field_color']['widget'];
  $el['#attributes']['class'][] = 'js-color-select2';

  //dpm($colors);
  //dpm('AAA');

  $el['#options'] = [];
  foreach ($colors as $color) {
    $colorCode = strtolower($color['color-code']);
    $tids = \Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'colors')
      ->condition('field_color_code', $colorCode)
      ->accessCheck(FALSE)
      ->execute();

    if (!empty($tids)) {
      $tid = reset($tids);
      $colorDetails = Term::load($tid);
      $el['#options'][$tid] = $colorDetails->label();
      $el['#option_attributes'][$tid]['data-color'] = $colorDetails->get('field_color_hex')->value;
      $hexCodes[$tid] = $colorDetails->get('field_color_hex')->value;
    }
  }

  $form['#attached']['library'][] = 'w_select_with_image/color_select2';
  $form['#attached']['drupalSettings']['colorSelect2'] = $hexCodes;

  $form['#attached']['drupalSettings']['availableColors'] = $colors;


  $form['popup'] = [
    '#type' => 'markup',
    '#markup' => '<div id="open-popup" class="button button--small">Place image on shirt</div>',
    '#weight' => 1,
  ];
}
